---
sudo: required
dist: xenial

language: python
python: "3.5"
services:
  - postgresql

before_install:
  - sudo apt-get update -qq

install:
  # Install ansible
  - pip3 install ansible yamllint

  # Create Nextcloud DB for testing
  - psql -c 'CREATE DATABASE nextcloud;' -U postgres

  # Add role dependency (mediafellows.nginx)
  - wget -O mediafellows.nginx.zip https://github.com/mediafellows/ansible-role-nginx/archive/master.zip && unzip mediafellows.nginx.zip
  - rm mediafellows.nginx.zip
  - mv ansible-role-nginx-master tests/roles/mediafellows.nginx

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

  # Debug output
  - ls tests/roles
  - ansible --version

  # Setup ruby to run serverspec tests
  - sudo ruby -v
  - sudo gem install serverspec

script:
  # Basic linting with yamllint
  - yamllint .

  # Ansible role syntax check
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Run the test playbook with ansible-playbook
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local

  # Run the test playbook again to check idempotence (allow 2 'changes' for status read)
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local
    | grep -q 'changed=2.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Some debug outputs
  - ls -lh /opt/nextcloud/
  - ls -lh /opt/nextcloud/config/
  - sudo cat /opt/nextcloud/config/config.php

  # Run serverspec as root to be able to test everything
  - sudo rake spec

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
