---
sudo: required
dist: xenial

language: python
python: "3.5"

before_install:
  - sudo apt-get update -qq

install:
  # Install ansible
  - pip3 install ansible yamllint

  # Add role dependency (mediafellows.nginx)
  - wget -O mediafellows.nginx.zip https://github.com/mediafellows/ansible-role-nginx/archive/master.zip && unzip mediafellows.nginx.zip
  - rm mediafellows.nginx.zip
  - mv ansible-role-nginx-master tests/roles/mediafellows.nginx

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

  # Debug output
  - ls tests/roles
  - ansible --version

script:
  # Basic linting with yamllint
  - yamllint .

  # Ansible role syntax check
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Run the test playbook with ansible-playbook
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local

  - ls /opt/
  - ls /tmp/

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
