---
# tasks file for mediafellows.nextcloud

- include_tasks: php_setup.yml
- include_tasks: nextcloud_setup.yml

- name: Trigger all notify handlers
  meta: flush_handlers

- name: Enable PHP FPM service
  service:
    name: '{{ nextcloud_php_version }}-fpm'
    state: started
    enabled: true
