---
# tasks file for mediafellows.nextcloud

- import_tasks: php_setup.yml

- import_tasks: nextcloud_setup.yml

- name: Trigger all notify handlers
  meta: flush_handlers

- name: Enable PHP FPM service
  service:
    name: 'php{{ nextcloud_php_version }}-fpm'
    state: started
    enabled: true
