---

- name: Download Nextcloud version {{ nextcloud_version }}
  get_url:
    url: 'https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.zip'
    dest: '/tmp/nextcloud.zip'

- name: Unzip Nextcloud package (contains nextcloud dir)
  unarchive:
    src: /tmp/nextcloud.zip
    dest: /tmp/
    remote_src: true

- name: Make sure Nextcloud install dir exists
  file:
    path: '{{ nextcloud_install_dir }}'
    state: directory
    owner: www-data
    group: www-data

- name: Move unzipped nextloud dir to install dir
  copy:
    src: /tmp/nextcloud
    dest: '{{ nextcloud_install_dir }}'
    remote_src: true
    owner: www-data
    group: www-data

- name: Cleanup install files
  file:
    path: /tmp/nextcloud.zip
    state: absent
- file:
    path: /tmp/nextcloud
    state: absent

- name: Copy config.php into place for initial setup
  template:
    src: nextcloud-config.php.j2
    dest: '{{ nextcloud_install_dir }}/config/config.php'

- name: Setup Nextcloud Data dir (for storing uploaded files) with Ngxinx permissions
  file:
    path: '{{ nextcloud_data_dir }}'
    state: directory
    owner: www-data
    group: www-data
