---

- name: Download Nextcloud version {{ nextcloud_version }}
  get_url:
    url: 'https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.zip'
    dest: '/tmp/nextcloud.zip'

- name: Test if requested version is already installed
  lineinfile:
    path: "{{ nextcloud_install_dir }}/version.php"
    line: "$OC_VersionString = '19.0.0';"
    state: present
  # only check if line would be added (when not present yet)
  check_mode: true
  # ingore errors, like when file doesn't exist yet
  ignore_errors: true
  register: has_version

- name: Set variable to determine if update/install needed
  set_fact:
    nextcloud_needs_install: "{{ has_version.changed|bool }}"

- set_fact:
    nextcloud_needs_install: true
  when: has_version.failed

- name: Output if install needed
  debug:
    var: nextcloud_needs_install

- name: Unzip Nextcloud package (contains nextcloud dir)
  unarchive:
    src: /tmp/nextcloud.zip
    dest: /tmp/
    remote_src: true
  when: nextcloud_needs_install

- name: Make sure Nextcloud parent dir exists
  file:
    path: '{{ nextcloud_install_dir | dirname }}'
    state: directory
  when: nextcloud_needs_install

- name: Move unzipped nextloud dir to install dir
  command: 'mv /tmp/nextcloud {{ nextcloud_install_dir }}'
  when: nextcloud_needs_install

- name: Move unzipped nextloud dir to install dir
  command: 'chown {{ nextcloud_user }}:{{ nextcloud_group }} -R {{ nextcloud_install_dir }}'
  when: nextcloud_needs_install

- name: Cleanup install files
  file:
    path: /tmp/nextcloud.zip
    state: absent

- name: Run OCC install task
  shell:
    cmd: |
      sudo -u {{ nextcloud_user }} php{{ nextcloud_php_version }} occ maintenance:install \
      --database "{{ nextcloud_db_type }}" \
      --database-host "{{ nextcloud_db_host }}:{{ nextcloud_db_port }}" \
      --database-name "{{ nextcloud_db_name }}" \
      --database-user "{{ nextcloud_db_user }}" \
      --database-pass "{{ nextcloud_db_pass }}" \
      --data-dir "{{ nextcloud_data_dir }}" \
      --admin-user "{{ nextcloud_initial_user_name }}" \
      --admin-pass "{{ nextcloud_initial_user_pw }}"
    chdir: "{{ nextcloud_install_dir }}"
    creates: "{{ nextcloud_install_dir }}/config/config.php"

- name: Setup Nextcloud Data dir (for storing uploaded files) with Ngxinx permissions
  file:
    path: '{{ nextcloud_data_dir }}'
    state: directory
    owner: "{{ nextcloud_user }}"
    group: "{{ nextcloud_group }}"
