---

- name: Add PHP PPA to allow installing of all recent PHP version
  apt_repository:
    repo: ppa:ondrej/php
    update_cache: true
    state: present

- name: Install PHP packages needed to run Nextcloud through Apt
  apt:
    name:
      # Essential PHP packages
      - 'php{{ nextcloud_php_version }}-common'
      - 'php{{ nextcloud_php_version }}-fpm'
      - 'php{{ nextcloud_php_version }}-cgi'
      - 'php{{ nextcloud_php_version }}-cli'
      - 'php-common'
      # Extra modules
      - 'php{{ nextcloud_php_version }}-curl'
      - 'php{{ nextcloud_php_version }}-gd'
      - 'php{{ nextcloud_php_version }}-json'
      - 'php{{ nextcloud_php_version }}-mbstring'
      - 'php{{ nextcloud_php_version }}-opcache'
      - 'php{{ nextcloud_php_version }}-readline'
      - 'php{{ nextcloud_php_version }}-xml'
      - 'php{{ nextcloud_php_version }}-zip'
      - 'php{{ nextcloud_php_version }}-intl'
      - 'php{{ nextcloud_php_version }}-bcmath'
      - 'php{{ nextcloud_php_version }}-gmp'
      - php-imagick
      # DB client lib
      - 'php{{ nextcloud_php_version }}-{{ nextcloud_db_type }}'
    state: present
  register: php_package_install
  notify:
    - restart php-fpm

- name: Update Memory limit in PHP ini
  lineinfile:
    path: /etc/php/{{ nextcloud_php_version }}/fpm/php.ini
    regex: '^memory_limit ='
    line: "memory_limit = {{ php_memory_limit }}"
  notify:
    - restart php-fpm

- name: Update OPcache settings in PHP ini
  blockinfile:
    path: /etc/php/{{ nextcloud_php_version }}/fpm/php.ini
    insertafter: ';opcache.enable=1'
    marker: '; -- Ansible managed block --'
    block: |
      opcache.enable=1
      opcache.interned_strings_buffer=8
      opcache.max_accelerated_files=10000
      opcache.memory_consumption=512
      opcache.save_comments=1
      opcache.revalidate_freq=2
  when: php_package_install.changed
